"""Generate and optionally run communication-operator microbenchmark scripts.

Generates torch.distributed scripts for HCCL communication benchmarking:
- all_reduce, all_gather, reduce_scatter, all_to_all
- Controls rank_group for topology_tier testing
- Outputs CSV in the format required by ProfilingDataSource (§4.7)

Design doc reference: §6.3 (Communication Microbenchmark)

CSV output format (§4.7):
    message_bytes,num_devices,dtype,topology_tier,Duration(us),bandwidth_gbps

Usage examples:
    # Generate scripts only
    python generate_comm_microbench.py --output-dir ./comm_scripts --num-devices 8 16

    # Generate scripts for all 4 ops, all topology tiers
    python generate_comm_microbench.py --output-dir ./comm_scripts \\
        --ops all_reduce all_gather reduce_scatter all_to_all \\
        --num-devices 2 4 8 16 32

    # Run directly and collect CSV (requires torch_npu + distributed env)
    torchrun --nproc_per_node=8 generate_comm_microbench.py \\
        --run --output-csv ./hccl_results.csv \\
        --ops all_reduce all_gather reduce_scatter all_to_all \\
        --topology-tier 2 --num-devices 8
"""

import argparse
import csv
import os
import sys
import time
from pathlib import Path
from textwrap import dedent
from typing import List, Optional

WARMUP_ITERS = 10
BENCH_ITERS = 100

_COMM_OPS = ["all_reduce", "all_gather", "reduce_scatter", "all_to_all"]

# message_bytes grid: 1KB ~ 512MB, powers of 4 (covers typical LLM TP/EP sizes)
_DEFAULT_BYTES_GRID = [
    1024,        # 1 KB
    4096,        # 4 KB
    16384,       # 16 KB
    65536,       # 64 KB
    262144,      # 256 KB
    1048576,     # 1 MB
    4194304,     # 4 MB
    16777216,    # 16 MB
    67108864,    # 64 MB
    268435456,   # 256 MB
    536870912,   # 512 MB
]

_DTYPE_ELEM_SIZE = {
    "torch.bfloat16": 2,
    "torch.float16": 2,
    "torch.float32": 4,
    "torch.int8": 1,
}

_DTYPE_TO_CSV = {
    "torch.bfloat16": "DT_BF16",
    "torch.float16": "DT_FP16",
    "torch.float32": "DT_FLOAT",
    "torch.int8": "DT_INT8",
}

# CSV columns per §4.7
_CSV_COLUMNS = ["message_bytes", "num_devices", "dtype", "topology_tier", "Duration(us)", "bandwidth_gbps"]


# ============================================================================
# Script generation (offline mode)
# ============================================================================

def _script_header(op_type: str, message_bytes: int, num_devices: int,
                   topology_tier: int, dtype: str) -> str:
    elem_size = _DTYPE_ELEM_SIZE.get(dtype, 2)
    num_elements = message_bytes // elem_size
    return dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"Auto-generated communication microbenchmark script.

        Op: {op_type}
        Message bytes: {message_bytes}
        Num devices: {num_devices}
        Topology tier: {topology_tier}
        Generated by: tools/perf_data_collection/generate_comm_microbench.py

        Run with:
            torchrun --nproc_per_node={num_devices} <this_script>.py [--output-csv results.csv]
        \"\"\"

        import argparse
        import csv
        import os
        import time
        from pathlib import Path
        import torch
        import torch.distributed as dist

        try:
            import torch_npu  # noqa: F401
            BACKEND = "hccl"
            DEVICE = "npu"
        except ImportError:
            BACKEND = "gloo"
            DEVICE = "cpu"
            print("WARNING: torch_npu not available, using gloo/CPU (results not meaningful)")

        WARMUP_ITERS = {WARMUP_ITERS}
        BENCH_ITERS = {BENCH_ITERS}
        MESSAGE_BYTES = {message_bytes}
        NUM_ELEMENTS = {num_elements}
        NUM_DEVICES = {num_devices}
        TOPOLOGY_TIER = {topology_tier}
        DTYPE = {dtype}
        DTYPE_CSV = "{_DTYPE_TO_CSV.get(dtype, 'DT_BF16')}"


        def setup():
            rank = int(os.environ.get("RANK", 0))
            world_size = int(os.environ.get("WORLD_SIZE", 1))
            if DEVICE == "npu":
                torch.npu.set_device(rank % torch.npu.device_count())
            dist.init_process_group(backend=BACKEND, rank=rank, world_size=world_size)
            return rank, world_size


        def bench(rank, world_size, output_csv=None):
            group_ranks = list(range(min(NUM_DEVICES, world_size)))
            group = dist.new_group(ranks=group_ranks)

            if rank not in group_ranks:
                return

    """)


def _op_body(op_type: str) -> str:
    """Return tensor setup + run_op() definition for each op type."""
    if op_type == "all_reduce":
        return dedent("""\
            tensor = torch.randn(NUM_ELEMENTS, dtype=DTYPE, device=DEVICE)

            def run_op():
                dist.all_reduce(tensor, group=group)
        """)
    elif op_type == "all_gather":
        return dedent("""\
            local_tensor = torch.randn(NUM_ELEMENTS, dtype=DTYPE, device=DEVICE)
            gather_list = [torch.empty_like(local_tensor) for _ in group_ranks]

            def run_op():
                dist.all_gather(gather_list, local_tensor, group=group)
        """)
    elif op_type == "reduce_scatter":
        return dedent("""\
            input_list = [torch.randn(NUM_ELEMENTS, dtype=DTYPE, device=DEVICE) for _ in group_ranks]
            output_tensor = torch.empty(NUM_ELEMENTS, dtype=DTYPE, device=DEVICE)

            def run_op():
                dist.reduce_scatter(output_tensor, input_list, group=group)
        """)
    elif op_type == "all_to_all":
        return dedent("""\
            per_rank = max(1, NUM_ELEMENTS // len(group_ranks))
            input_list = [torch.randn(per_rank, dtype=DTYPE, device=DEVICE) for _ in group_ranks]
            output_list = [torch.empty(per_rank, dtype=DTYPE, device=DEVICE) for _ in group_ranks]

            def run_op():
                dist.all_to_all(output_list, input_list, group=group)
        """)
    else:
        raise ValueError(f"Unknown op_type: {op_type}")


def _bench_tail(op_type: str) -> str:
    return dedent(f"""\
            # Warmup
            for _ in range(WARMUP_ITERS):
                run_op()
            if DEVICE == "npu":
                torch.npu.synchronize()

            # Benchmark
            if DEVICE == "npu":
                torch.npu.synchronize()
            start = time.perf_counter()
            for _ in range(BENCH_ITERS):
                run_op()
            if DEVICE == "npu":
                torch.npu.synchronize()
            elapsed = time.perf_counter() - start

            duration_us = elapsed / BENCH_ITERS * 1e6
            bandwidth_gbps = MESSAGE_BYTES / (duration_us * 1e-6) / 1e9

            if rank == 0:
                op_name = "{op_type}"
                print(f"op={{op_name}}  bytes={{MESSAGE_BYTES}}  devices={{len(group_ranks)}}"
                      f"  tier={{TOPOLOGY_TIER}}  duration={{duration_us:.2f}}us  bw={{bandwidth_gbps:.2f}}GB/s")
                if output_csv:
                    write_header = not Path(output_csv).exists()
                    with open(output_csv, "a", newline="") as f:
                        w = csv.writer(f)
                        if write_header:
                            w.writerow(["message_bytes", "num_devices", "dtype",
                                        "topology_tier", "Duration(us)", "bandwidth_gbps"])
                        w.writerow([MESSAGE_BYTES, len(group_ranks), DTYPE_CSV,
                                    TOPOLOGY_TIER, f"{{duration_us:.2f}}", f"{{bandwidth_gbps:.2f}}"])


        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument("--output-csv", default=None)
            args = parser.parse_args()
            rank, world_size = setup()
            try:
                bench(rank, world_size, output_csv=args.output_csv)
            finally:
                dist.destroy_process_group()


        if __name__ == "__main__":
            main()
    """)


def generate_comm_script(op_type: str, message_bytes: int, num_devices: int,
                         topology_tier: int = 2, dtype: str = "torch.bfloat16") -> str:
    """Generate a self-contained communication benchmark script.

    Args:
        op_type: One of all_reduce, all_gather, reduce_scatter, all_to_all
        message_bytes: Total message size in bytes
        num_devices: Number of devices in the communicator group
        topology_tier: 0=inter_pod, 1=intra_pod, 2=die_level (ATLAS_800_A3)
        dtype: Tensor dtype string
    """
    header = _script_header(op_type, message_bytes, num_devices, topology_tier, dtype)
    op_body = _indent(_op_body(op_type), 4)
    tail = _bench_tail(op_type)
    return header + op_body + "\n" + tail


def _indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines()) + "\n"


# ============================================================================
# Direct run mode (--run)
# ============================================================================

def run_benchmark(op_type: str, message_bytes: int, num_devices: int,
                  topology_tier: int, dtype_str: str, output_csv: Optional[str]) -> Optional[dict]:
    """Run a single benchmark directly in the current process.

    Requires torch_npu + initialized distributed environment (torchrun).
    Returns result dict or None if rank not in group.
    """
    try:
        import torch
        import torch.distributed as dist
    except ImportError:
        print("ERROR: torch not available", file=sys.stderr)
        return None

    try:
        import torch_npu  # noqa: F401
        device = "npu"
    except ImportError:
        device = "cpu"

    rank = dist.get_rank()
    world_size = dist.get_world_size()

    group_ranks = list(range(min(num_devices, world_size)))
    group = dist.new_group(ranks=group_ranks)

    if rank not in group_ranks:
        return None

    import torch
    dtype = getattr(torch, dtype_str.replace("torch.", ""))
    elem_size = _DTYPE_ELEM_SIZE.get(dtype_str, 2)
    num_elements = message_bytes // elem_size

    # Build tensors
    if op_type == "all_reduce":
        tensor = torch.randn(num_elements, dtype=dtype, device=device)
        def run_op(): dist.all_reduce(tensor, group=group)
    elif op_type == "all_gather":
        local_tensor = torch.randn(num_elements, dtype=dtype, device=device)
        gather_list = [torch.empty_like(local_tensor) for _ in group_ranks]
        def run_op(): dist.all_gather(gather_list, local_tensor, group=group)
    elif op_type == "reduce_scatter":
        input_list = [torch.randn(num_elements, dtype=dtype, device=device) for _ in group_ranks]
        output_tensor = torch.empty(num_elements, dtype=dtype, device=device)
        def run_op(): dist.reduce_scatter(output_tensor, input_list, group=group)
    elif op_type == "all_to_all":
        per_rank = max(1, num_elements // len(group_ranks))
        input_list = [torch.randn(per_rank, dtype=dtype, device=device) for _ in group_ranks]
        output_list = [torch.empty(per_rank, dtype=dtype, device=device) for _ in group_ranks]
        def run_op(): dist.all_to_all(output_list, input_list, group=group)
    else:
        raise ValueError(f"Unknown op_type: {op_type}")

    # Warmup
    for _ in range(WARMUP_ITERS):
        run_op()
    if device == "npu":
        torch.npu.synchronize()

    # Benchmark
    if device == "npu":
        torch.npu.synchronize()
    start = time.perf_counter()
    for _ in range(BENCH_ITERS):
        run_op()
    if device == "npu":
        torch.npu.synchronize()
    elapsed = time.perf_counter() - start

    duration_us = elapsed / BENCH_ITERS * 1e6
    bandwidth_gbps = message_bytes / (duration_us * 1e-6) / 1e9

    result = {
        "message_bytes": message_bytes,
        "num_devices": len(group_ranks),
        "dtype": _DTYPE_TO_CSV.get(dtype_str, "DT_BF16"),
        "topology_tier": topology_tier,
        "Duration(us)": round(duration_us, 2),
        "bandwidth_gbps": round(bandwidth_gbps, 2),
    }

    if rank == 0:
        print(f"op={op_type}  bytes={message_bytes}  devices={len(group_ranks)}"
              f"  tier={topology_tier}  duration={duration_us:.2f}us  bw={bandwidth_gbps:.2f}GB/s")
        if output_csv:
            _append_csv(output_csv, result)

    return result


def _append_csv(path: str, row: dict) -> None:
    p = Path(path)
    write_header = not p.exists()
    with p.open("a", newline="") as f:
        w = csv.DictWriter(f, fieldnames=_CSV_COLUMNS)
        if write_header:
            w.writeheader()
        w.writerow(row)


# ============================================================================
# CLI
# ============================================================================

def build_argparser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate or run HCCL communication microbenchmarks.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent("""\
            Examples:
              # Generate scripts for all ops, 2 device counts
              python generate_comm_microbench.py --output-dir ./scripts --num-devices 8 16

              # Generate for all 4 ops + all topology tiers
              python generate_comm_microbench.py --output-dir ./scripts \\
                  --ops all_reduce all_gather reduce_scatter all_to_all \\
                  --num-devices 2 4 8 16 32 --topology-tier 0 1 2

              # Run directly (requires torchrun)
              torchrun --nproc_per_node=8 generate_comm_microbench.py \\
                  --run --output-csv ./hccl_v8.5/hcom_allReduce_.csv \\
                  --ops all_reduce --num-devices 8 --topology-tier 2
        """),
    )
    parser.add_argument(
        "--output-dir",
        default="./comm_scripts",
        help="Directory to write generated benchmark scripts (default: ./comm_scripts)",
    )
    parser.add_argument(
        "--ops",
        nargs="+",
        default=_COMM_OPS,
        choices=_COMM_OPS,
        help="Communication ops to benchmark (default: all 4)",
    )
    parser.add_argument(
        "--num-devices",
        type=int,
        nargs="+",
        default=[8, 16],
        help="Number of devices per communicator group (default: 8 16)",
    )
    parser.add_argument(
        "--topology-tier",
        type=int,
        nargs="+",
        default=[2],
        help="Topology tier(s): 0=inter_pod 1=intra_pod 2=die_level (default: 2)",
    )
    parser.add_argument(
        "--dtype",
        default="torch.bfloat16",
        choices=list(_DTYPE_ELEM_SIZE.keys()),
        help="Tensor dtype (default: torch.bfloat16)",
    )
    parser.add_argument(
        "--bytes-grid",
        type=int,
        nargs="+",
        default=None,
        help="Custom message_bytes grid (default: 1KB~512MB powers-of-4)",
    )
    # Run mode
    parser.add_argument(
        "--run",
        action="store_true",
        help="Run benchmarks directly instead of generating scripts (requires torchrun)",
    )
    parser.add_argument(
        "--output-csv",
        default=None,
        help="CSV file to append results to (used with --run, format per §4.7)",
    )
    return parser


def main() -> None:
    args = build_argparser().parse_args()
    bytes_grid = args.bytes_grid or _DEFAULT_BYTES_GRID

    if args.run:
        # Direct run mode — requires initialized distributed env
        try:
            import torch.distributed as dist
            if not dist.is_initialized():
                dist.init_process_group(backend="hccl" if _has_torch_npu() else "gloo")
        except Exception as e:
            print(f"ERROR: Failed to initialize distributed: {e}", file=sys.stderr)
            print("Hint: run with `torchrun --nproc_per_node=N generate_comm_microbench.py --run ...`",
                  file=sys.stderr)
            sys.exit(1)

        total = 0
        for op_type in args.ops:
            for num_devices in args.num_devices:
                for topology_tier in args.topology_tier:
                    for msg_bytes in bytes_grid:
                        run_benchmark(op_type, msg_bytes, num_devices,
                                      topology_tier, args.dtype, args.output_csv)
                        total += 1

        import torch.distributed as dist
        dist.destroy_process_group()
        if dist.get_rank() == 0:
            print(f"\nCompleted {total} benchmarks."
                  + (f" Results saved to {args.output_csv}" if args.output_csv else ""))
    else:
        # Script generation mode
        output_dir = Path(args.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        count = 0

        for op_type in args.ops:
            for num_devices in args.num_devices:
                for topology_tier in args.topology_tier:
                    for msg_bytes in bytes_grid:
                        script = generate_comm_script(
                            op_type, msg_bytes, num_devices, topology_tier, args.dtype
                        )
                        fname = f"comm_{op_type}_B{msg_bytes}_D{num_devices}_T{topology_tier}.py"
                        (output_dir / fname).write_text(script)
                        count += 1

        print(f"Generated {count} communication benchmark scripts in {output_dir}")
        print(f"  ops: {args.ops}")
        print(f"  num_devices: {args.num_devices}")
        print(f"  topology_tiers: {args.topology_tier}")
        print(f"  message_bytes: {len(bytes_grid)} sizes ({bytes_grid[0]}~{bytes_grid[-1]} bytes)")
        print()
        print("To run a script:")
        print(f"  torchrun --nproc_per_node=<N> {output_dir}/comm_<op>_B<bytes>_D<N>_T<tier>.py --output-csv results.csv")


def _has_torch_npu() -> bool:
    try:
        import torch_npu  # noqa: F401
        return True
    except ImportError:
        return False


if __name__ == "__main__":
    main()
